# Generated by Django 4.1.7 on 2023-03-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('birthdate', models.DateField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Student_type', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=13)),
                ('has_Form_137', models.BooleanField(default=False)),
                ('PSA_or_NSO', models.BooleanField(default=False)),
                ('_2x2_picture', models.BooleanField(default=False)),
                ('Certificate_of_Good_Morale', models.BooleanField(default=False)),
            ],
        ),
    ]
