# Generated by Django 4.1.7 on 2023-03-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='has_Form_137',
            new_name='Form_137',
        ),
    ]
