# Generated by Django 4.1.7 on 2023-03-28 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_subjects_alter_professor_age'),
        ('students', '0001_initial'),
        ('subjects', '0002_subject_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='professor_assigned',
            field=models.ManyToManyField(related_name='SubjectProfessor_professor_assigned', through='subjects.SubjectProfessor', to='professor.professor'),
        ),
        migrations.CreateModel(
            name='SubjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
    ]
