# Generated by Django 4.1.7 on 2023-03-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_2x2 photo submitted_student_goodmorale_done_and_more'),
        ('subjects', '0005_rename_professor_assigned_subject_professors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='SubjectProfessor_student_assigned', through='subjects.SubjectStudent', to='students.student'),
        ),
    ]
