# Generated by Django 4.1.7 on 2023-03-28 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_subjects_alter_professor_age'),
        ('students', '0003_rename_2x2 photo submitted_student_goodmorale_done_and_more'),
        ('subjects', '0007_subjectprofessor_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectprofessor',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='subjectstudent',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='subjectprofessor',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='subjectstudent',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='subjectprofessor',
            name='professor_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professor.professor'),
        ),
        migrations.AlterField(
            model_name='subjectstudent',
            name='student_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
