# Generated by Django 4.1.7 on 2023-03-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_date_updated_and_more'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='subjects',
            field=models.ManyToManyField(through='subjects.SubjectProfessor', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='age',
            field=models.IntegerField(),
        ),
    ]
