# Generated by Django 4.1.7 on 2023-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0003_alter_subject_professor_assigned_subjectstudent'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(through='subjects.SubjectStudent', to='subjects.subject'),
        ),
    ]
