# Generated by Django 4.1.7 on 2023-03-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='2x2 Photo Submitted',
            new_name='GoodMorale_done',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Certificate of Good Moral Submitted',
            new_name='PSA_done',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Form 137 Submitted',
            new_name='TwoByTwo_done',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='PSA/NSO Submitted',
            new_name='form137_done',
        ),
    ]
